from enum import Enum


class ScreenName(Enum):
    MAIN_MENU = 1
    MULTIPLAYER_MENU = 2
    GAME = 3
    GAME_OVER = 4
    CREDITS = 5
    OPTIONS = 6
    CONTROLS = 7
    PAUSE = 8
    MULTIPLAYER = 9
    MULTIPLAYER_GAME = 10
    MULTIPLAYER_GAME_OVER = 11
    MULTIPLAYER_CREDITS = 12
    MULTIPLAYER_OPTIONS = 13
    MULTIPLAYER_CONTROLS = 14
    MULTIPLAYER_PAUSE = 15
